@URL = https://bceauu9hb6.execute-api.eu-west-1.amazonaws.com/


### Get all users
GET {{URL}}/users

### Create a user
POST {{URL}}/users
Content-Type: application/json

{
    "name": "nick",
    "email": "coding@addict.com"
}

### Get a user
GET {{URL}}/users/d096448c-8be7-459a-8351-812fb52dcd25

### Update a user
PUT {{URL}}/users/d096448c-8be7-459a-8351-812fb52dcd25
Content-Type: application/json

{
    "name": "coding addict",
    "email": "coding@addict.com"
}

### Delete a user
DELETE {{URL}}/users/ad055d23-324e-4927-b941-10f3c1bb5b4b
